config/routes.rb
KanbanBoard::Application.routes.draw do

  resource :home, :only => [:show], :controller => 'home'

  resources :projects do
    resources :statuses
    resources :members, :only => [:index, :new, :create, :destroy]
    resources :user_stories, :except => [:index, :show] do
      post 'update_status', :on => :collection
      resources :issues, :except => [:index, :show]
    end
  end

  resources :users, :only => [:create]
  match "signup" => "users#new"
  resource :account, :only => [:show, :edit, :update, :destroy], :controller => 'users'
  resource :password, :only => [:edit, :update], :controller => 'user_password'
  resources :reset_passwords, :only => [:new, :create, :edit, :update]

  resources :sessions, :only => [:create]
  match "login" => "sessions#new"
  match "logout" => "sessions#destroy"

  resources :invitations, :only => [:create, :update, :destroy]

  root :to => 'home#show'
end

app/models/user_story.rb
class UserStory < ActiveRecord::Base
  belongs_to :project
  belongs_to :status
  belongs_to :story_size
  has_many :issues
  acts_as_list :scope => :status

  validates :name, :presence => true
  validates :description, :presence => true

  def size
    if story_size
      story_size.name.slice(0)
    else
      '?'
    end
  end

  def size_alias
    if story_size
      story_size.name.downcase.gsub(' ','_')
    end
  end

end

app/controllers/user_stories_controller.rb
class UserStoriesController < ApplicationController
  before_filter :require_login
  load_and_authorize_resource :project
  load_and_authorize_resource :user_story, :through => :project
  before_filter :load_resources

  def new
    @user_story = @project.user_stories.build
  end

  def create
    @user_story = @project.user_stories.build(params[:user_story])
    if @user_story.save
      respond_to do |format|
      format.html { redirect_to @project, :notice => 'User Story Created!'}
      format.js { @user_story }
      end
    else
      respond_to do |format|
      format.html { render :new }
      format.js { @user_story }
      end
    end
  end

  def edit
    @user_story = UserStory.find(params[:id])
  end

  def update
    @user_story = UserStory.find(params[:id])
    if @user_story.update_attributes(params[:user_story])
      respond_to do |format|
      format.html { redirect_to @project, :notice => 'User Story Updated!'}
      format.js { @user_story }
      end
    else
      respond_to do |format|
      format.html { render :edit }
      format.js { @user_story }
      end
    end
  end

  def destroy
    @user_story = UserStory.find(params[:id])
      if @user_story.destroy
      respond_to do |format|
      format.html { redirect_to @project, :notice => 'User Story Deleted!'}
      format.js { @user_story }
      end
    else
      redirect_to @project
    end
  end

  def update_status
    if params[:status] && params[:user_story]
      status = params[:status]
      params[:user_story].each_with_index do |id, index|
        UserStory.update_all({status_id: status, position: (index+1)},{id: id})
      end
    end
    render nothing: true
  end

  private

  def load_resources
    @project = Project.find(params[:project_id])
    @statuses = @project.statuses
    @story_sizes = StorySize.all
  end

end

app/helpers/user_stories_helper.rb
module UserStoriesHelper

  def highlight_user_story(text)
    highlighter = '<mark>\1</mark>'
    matchers = [/(In order to)/, /(As an?)/, /(I want to)/]
    matchers.each do |matcher|
      text.gsub!(matcher, highlighter)
    end
    simple_format(text, {},:sanitize => false)
  end

  # For AJAX CRUD

  def status_list
    "td#status_#{@user_story.status.id} ul"
  end

  def user_story_item
    "li#user_story_#{@user_story.id}"
  end

end

app/views/user_stories/_form.html.haml
= error_messages_for(user_story)
=form_for([project, user_story], :remote => true) do |f|
  %div
    =f.label :name
    =f.text_field :name, :autofocus => true
  %div
    =f.label :description
    =f.text_area :description, :rows => '6'
  %div
    =f.label :story_size_id, 'Story Size'
    =f.collection_select(:story_size_id, story_sizes, :id, :name, :include_blank => '?')
  %div#status
    =f.label :status_id
    =f.collection_select(:status_id, statuses, :id, :name)
  %div
    =f.submit :class => 'btn'

app/views/user_stories/_user_story.html.haml
%li{:id => ['user_story', user_story.id], :class => "user_stories"}
  %header{ :class => "#{user_story.size_alias}" }
    %h4= user_story.name
    %span.story_size= user_story.size
  %div.details= highlight_user_story(user_story.description)
  -if user_story.issues.any?
    %div.issues
      %h5 Blocking Issues
      =render user_story.issues, :project => project, :user_story => user_story
  %footer
    = link_to 'Block', new_project_user_story_issue_path(project, user_story), :remote => true
    = link_to 'Delete', project_user_story_path(project, user_story), :remote => true, :method => :delete, :confirm => 'Are you sure?'
    = link_to 'Edit', edit_project_user_story_path(project, user_story), :remote => true

app/views/user_stories/edit.html.haml
%h2 Edit User Story
=render 'form', :project => @project, :user_story => @user_story, :story_sizes => @story_sizes, :statuses => @statuses

app/views/user_stories/new.html.haml
%h2 New User Story
=render 'form', :project => @project, :user_story => @user_story, :story_sizes => @story_sizes, :statuses => @statuses