config/routes.rb
KanbanBoard::Application.routes.draw do

  resource :home, :only => [:show], :controller => 'home'

  resources :projects do
    resources :statuses
    resources :members, :only => [:index, :new, :create, :destroy]
    resources :user_stories, :except => [:index, :show] do
      post 'update_status', :on => :collection
      resources :issues, :except => [:index, :show]
    end
  end

  resources :users, :only => [:create]
  match "signup" => "users#new"
  resource :account, :only => [:show, :edit, :update, :destroy], :controller => 'users'
  resource :password, :only => [:edit, :update], :controller => 'user_password'
  resources :reset_passwords, :only => [:new, :create, :edit, :update]

  resources :sessions, :only => [:create]
  match "login" => "sessions#new"
  match "logout" => "sessions#destroy"

  resources :invitations, :only => [:create, :update, :destroy]

  root :to => 'home#show'
end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  before_filter :load_project

  def index
    @statuses = @project.statuses
  end

  def new
    @status = @project.statuses.build
  end

  def create
    @status = @project.statuses.build(params[:status])
    if @status.save
      flash[:notice] = 'Status was created!'
      redirect_to project_statuses_path(@project)
    else
      render :new
    end
  end

  def edit
    @status = Status.find(params[:id])
  end

  def update
    @status = Status.find(params[:id])
    if @status.update_attributes(params[:status])
      flash[:notice] = 'Status was updated!'
      redirect_to project_statuses_path(@project)
    else
      render :edit
    end
  end

  def destroy
    @status = Status.find(params[:id])
    if @status.destroy
      flash[:notice] = 'Status was deleted!'
      redirect_to project_statuses_path(@project)
    else
      redirect_to project_statuses_path(@project)
    end
  end

  private

  def load_project
    @project = Project.find(params[:project_id])
  end

end

app/views/statuses/_form.html.haml
= error_messages_for(status)
= form_for([project, status]) do |f|
  %div
    =f.label :name
    =f.text_field :name
  %div
    =f.label :wip, 'Work in Progress Limit'
    =f.text_field :wip
  %div
    =f.submit :class => 'btn'

app/views/statuses/_status.html.haml
%td{ :id => ['status', status.id] }
  %header
    %h3= status.name
    - if status.wip
      %span.wip= "WIP: #{status.wip}"
  %ul.unstyled{ 'data-update-url' => update_status_project_user_stories_path(project, :status => status.id)}
    =render :partial => 'user_stories/user_story', :collection => status.user_stories, :locals => { :project => project }
    %li.show_more_user_stories Show more User Stories

app/views/statuses/edit.html.haml
%h2 Edit Status
= render 'form', :project => @project, :status => @status

app/views/statuses/index.html.haml
%h1 Statuses
%table.table.table-bordered.table-striped.table-condensed
  %thead
    %tr
      %th Name
      %th WIP
      %th Manage
  %tbody
    - @statuses.each do |status|
      %tr{ :id => ['status', status.id] }
        %td= status.name
        %td= status.wip
        %td
          %div.btn-group
            = link_to edit_project_status_path(@project, status), :class => 'btn' do
              %i.icon-pencil
              Edit
            = link_to project_status_path(@project, status), :method => :delete, :confirm => 'Are you sure?', :class => 'btn btn-danger' do
              %i.icon-trash.icon-white
              Delete
= link_to new_project_status_path(@project), :class => 'btn btn-success' do
  %i.icon-plus.icon-white
  Add Status

app/views/statuses/new.html.haml
%h2 New Status
=form_for [@project,@status] do |f|
  %table
    %thead
      %tr
        %th= f.label :name
        %th= f.label :wip, 'Work in Progress Limit'
        - if params[:action] == 'edit'
          %th= f.label :_destroy, 'Delete'
    %tbody
      =render 'form', :f => f
  =f.submit :class => 'button'