config/routes.rb
KanbanBoard::Application.routes.draw do

  resource :home, :only => [:show], :controller => 'home'

  resources :projects do
    resources :statuses
    resources :members, :only => [:index, :new, :create, :destroy]
    resources :user_stories, :except => [:index, :show] do
      post 'update_status', :on => :collection
      resources :issues, :except => [:index, :show]
    end
  end

  resources :users, :only => [:create]
  match "signup" => "users#new"
  resource :account, :only => [:show, :edit, :update, :destroy], :controller => 'users'
  resource :password, :only => [:edit, :update], :controller => 'user_password'
  resources :reset_passwords, :only => [:new, :create, :edit, :update]

  resources :sessions, :only => [:create]
  match "login" => "sessions#new"
  match "logout" => "sessions#destroy"

  resources :invitations, :only => [:create, :update, :destroy]

  root :to => 'home#show'
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!
  has_many :memberships, :dependent => :destroy
  has_many :projects, :through => :memberships

  attr_accessible :name, :email, :password, :password_confirmation

  EMAIL_REGEX = /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i

  validates :name,      :presence => true

  validates :password,  :presence => true,
                        :length => 3..20,
                        :confirmation => true,
                        :on => :create
  validates :email,     :presence => true,
                        :format => EMAIL_REGEX,
                        :uniqueness => {:case_sensitive => false}

  def self.search(query)
    if query.match(EMAIL_REGEX)
     where('email = ?', query)
    else
      raise InvalidEmailFormat
    end
  end

  def invitations
    Invitation.search(email)
  end

  class InvalidEmailFormat < StandardError
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :require_login, :only => [:show, :edit, :update]

  def show
    @user = current_user
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      auto_login(@user)
      remember_me!
      redirect_to projects_path, :notice => "Signed up!"
    else
      render :new
    end
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update_attributes(params[:user])
      redirect_to projects_path, :notice => 'Your account was updated!'
    else
      render :Edit
    end
  end

  def destroy
    @user = current_user
    if @user.destroy
      redirect_to root_path, :notice => 'Your account was deleted!'
    end
  end

end

app/views/users/edit.html.haml
%h2 Edit Account
= error_messages_for(@user)
= form_for @user, :url => account_path do |f|
  %div
    =f.label :name
    =f.text_field :name
  %div
    =f.label :email
    =f.text_field :email
  %div=f.submit 'Update Account', :class => 'btn'

app/views/users/new.html.haml
%h2 Sign Up
= error_messages_for(@user)
=form_for @user do |f|
  %div
    =f.label :name
    =f.text_field :name
  %div
    =f.label :email
    =f.text_field :email
  %div
    =f.label :password
    =f.password_field :password
  %div
    =f.label :password_confirmation
    =f.password_field :password_confirmation
  %div=f.submit 'Sign Up', :class => 'btn'

app/views/users/show.html.haml
%h2 My Account
%dl
  %dt
    %strong Name
  %dd= @user.name
  %dt
    %strong Email
  %dd= @user.email
=link_to 'Edit', edit_account_path, :class => 'btn'
=link_to 'Change Password', edit_password_path, :class => 'btn'
=link_to 'Delete Account', account_path, :class => 'btn btn-danger', :method => :delete, :confirm => 'Are you sure?'