config/routes.rb
KanbanBoard::Application.routes.draw do

  resource :home, :only => [:show], :controller => 'home'

  resources :projects do
    resources :statuses
    resources :members, :only => [:index, :new, :create, :destroy]
    resources :user_stories, :except => [:index, :show] do
      post 'update_status', :on => :collection
      resources :issues, :except => [:index, :show]
    end
  end

  resources :users, :only => [:create]
  match "signup" => "users#new"
  resource :account, :only => [:show, :edit, :update, :destroy], :controller => 'users'
  resource :password, :only => [:edit, :update], :controller => 'user_password'
  resources :reset_passwords, :only => [:new, :create, :edit, :update]

  resources :sessions, :only => [:create]
  match "login" => "sessions#new"
  match "logout" => "sessions#destroy"

  resources :invitations, :only => [:create, :update, :destroy]

  root :to => 'home#show'
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :statuses, :dependent => :destroy
  has_many :user_stories, :dependent => :destroy
  has_many :memberships, :dependent => :destroy
  has_many :invitations, :dependent => :destroy
  has_many :users, :through => :memberships

  after_create :create_backlog

  validates :name, :presence => true
  validates :description, :presence => true

  def member?(user)
    users.exists?(user.id)
  end

  def remove_member(user)
    memberships.where('user_id = ?', user.id).first.destroy
  end

  def create_backlog
    statuses.create( :name => 'Backlog')
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :require_login
  load_and_authorize_resource

  def index
    @projects = current_user.projects
    @invitations = current_user.invitations
  end

  def show
    @project = Project.find(params[:id])
    @statuses = @project.statuses
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(params[:project])
    if @project.save
      current_user.projects << @project
      redirect_to projects_path, :notice => 'Project Created!'
    else
      render :new
    end
  end

  def edit
    @project = Project.find(params[:id])
  end

  def update
    @project = Project.find(params[:id])
    if @project.update_attributes(params[:project])
      redirect_to projects_path, :notice => 'Project Updated!'
    else
      render :edit
    end
  end

  def destroy
    @project = Project.find(params[:id])
    if @project.destroy
      redirect_to projects_path, :notice => 'Project Deleted!'
    else
      render :index
    end
  end

  private

end

app/views/projects/_form.html.haml
= error_messages_for(project)
= form_for project do |f|
  %div
    =f.label :name
    =f.text_field :name, :autofocus => true
  %div
    =f.label :description
    =f.text_area :description, :rows => '6'
  %div
    =f.submit :class => 'btn'

app/views/projects/_project.html.haml
%tr{:id => ['project', project.id]}
  %td.project_info
    %h3= link_to project.name, project_path(project)
    %div.project_description= project.description
  %td
    %ul.unstyled
      - project.statuses.each do |status|
        %li
          = status.name
  %td
    %ul.unstyled.project_user_stories
      - project.statuses.each do |status|
        %li
          = status.user_stories.count
  %td
    %ul.unstyled.project_statuses_availability
      - project.statuses.each do |status|
        %li
          = status.availability
  %td
    %ul.unstyled
      - project.users.each do |member|
        %li= member.name
  %td.project_actions
    %ul.unstyled
      %li= link_to 'edit project', edit_project_path(project)
      %li= link_to 'statuses', project_statuses_path(project)
      %li= link_to 'members', project_members_path(project)
      %li= link_to 'delete project', project_path(project), :method => :delete, :confirm => 'Are you sure?'

app/views/projects/edit.html.haml
%h2 Edit Project
=render 'form', :project => @project, :statuses => @statuses

app/views/projects/index.html.haml
- if @invitations.any?
  %h1 Invitations
  %ul#invitation_list
    = render @invitations
%h1 Projects
%table.table.table-bordered.table-striped
  %thead
    %th.project_name Name
    %th Statuses
    %th User Stories
    %th Availability
    %th Members
    %th Manage
  %tbody
    = render @projects
- if @projects.empty?
  %div.empty_list No projects yet
= link_to new_project_path, :class => 'btn btn-success' do
  %i.icon-plus.icon-white
  New Project

app/views/projects/new.html.haml
%h2 New Project
=render 'form', :project => @project, :statuses => @statuses

app/views/projects/show.html.haml
.rpw
  %h2.pull-left= @project.name
  .pull-right
    = link_to new_project_user_story_path(@project), :remote => true, :class => 'btn btn-success', :id => 'new_story' do
      %i.icon-plus.icon-white
      New User Story
%div#board
  %table
    %tbody
      =render @statuses, :project => @project